# This service drives the robot with the given forward, horizontal, and turning powers
float32 horizontal_power # duty cycle
float32 forward_power # duty cycle
float32 turning_power # duty cycle
---
int32 success