ARG FROM_IMAGE=ros:humble
ARG OVERLAY_WS=/opt/ros/overlay_ws

# multi-stage for caching
FROM $FROM_IMAGE AS cacher

# clone overlay source
ARG OVERLAY_WS
WORKDIR $OVERLAY_WS/src
RUN echo "\
repositories: \n\
  GOFIRST-Robotics/LUNABOTICS-2023: \n\
    type: git \n\
    url: https://github.com/GOFIRST-Robotics/LUNABOTICS-2023.git \n\
    version: main \n\
" > ../overlay.repos
RUN vcs import ./ < ../overlay.repos

# copy manifests for caching
WORKDIR /opt
RUN mkdir -p /tmp/opt && \
    find ./ -name "package.xml" | \
      xargs cp --parents -t /tmp/opt && \
    find ./ -name "COLCON_IGNORE" | \
      xargs cp --parents -t /tmp/opt || true

# multi-stage for building
FROM $FROM_IMAGE AS builder

# install overlay dependencies
ARG OVERLAY_WS
WORKDIR $OVERLAY_WS
COPY --from=cacher /tmp/$OVERLAY_WS/src ./src
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    apt-get update && rosdep install -i \
    --from-path src --rosdistro humble -y \
    && rm -rf /var/lib/apt/lists/*

# Install pip dependencies
RUN apt-get update && apt-get install -y \
    python3-pip
# This is the latest version of the setuptools library that ROS2 currently supports
RUN pip install setuptools==58.2.0

# build overlay source
COPY --from=cacher $OVERLAY_WS/src ./src
ARG OVERLAY_MIXINS="release"
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build \
      --packages-select \
        navx_cpp_package \
        motor_control \
        rovr_control \
      --mixin $OVERLAY_MIXINS

# source entrypoint setup
ENV OVERLAY_WS $OVERLAY_WS
RUN sed --in-place --expression \
      '$isource "$OVERLAY_WS/install/setup.bash"' \
      /ros_entrypoint.sh

# initialize our CAN bridge submodule
RUN cd src/GOFIRST-Robotics/LUNABOTICS-2023 && git submodule init && git submodule update
RUN apt-get install libboost-all-dev -y

# install overlay dependencies again
ARG OVERLAY_WS
WORKDIR $OVERLAY_WS
COPY --from=cacher /tmp/$OVERLAY_WS/src ./src
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    apt-get update && rosdep install -i \
    --from-path src --rosdistro humble -y \
    && rm -rf /var/lib/apt/lists/*

# build overlay source again (to build the CAN bridge submodule)
COPY --from=cacher $OVERLAY_WS/src ./src
ARG OVERLAY_MIXINS="release"
RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build \
      --packages-select \
        ros2socketcan_bridge \
      --mixin $OVERLAY_MIXINS