<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by
Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-4-g7f85cfe  Build Version: 1.6.7995.38578
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->

<robot name="master_ASM" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="robot.urdf.xacro" />

  <link name="base_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </link>

  <joint name="base_to_frame_joint" type="fixed">
    <parent link="base_link" />
    <child link="frame_link" />
    <origin xyz="0 0 0" rpy="0 0 ${-pi/2}" />
  </joint>

  <!-- ZED 2i Camera -->
  <xacro:include filename="zed.urdf.xacro" />
 
  <gazebo reference="zed2i_camera_link">
    <sensor name="camera" type="camera">
      <!-- <visualize>true</visualize> -->
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.91986218</horizontal_fov> 
        <image>
          <format>R8G8B8</format>
          <width>1280</width>
          <height>720</height>
        </image>
        <clip>
          <near>0.3</near>
          <far>5.0</far>
        </clip>
      </camera>
      <topic>/color/image</topic>
      <info_topic>/color/camera_info</info_topic>
      <gz_frame_id>zed2i_left_camera_optical_frame</gz_frame_id>
    </sensor>
    <sensor name="depthcamera" type="depth">
      <!-- <visualize>true</visualize> -->
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.91986218</horizontal_fov> 
        <image>
          <format>R8G8B8</format>
          <width>1280</width>
          <height>720</height>
        </image>
        <clip>
          <near>0.3</near>
          <far>20.0</far>
        </clip>
      </camera>
      <topic>/depth/image</topic>
      <info_topic>/depth/camera_info</info_topic>
      <gz_frame_id>zed2i_left_camera_optical_frame</gz_frame_id>
    </sensor>
  </gazebo>

  <gazebo>
        <plugin
        filename="ignition-gazebo-joint-state-publisher-system"
        name="ignition::gazebo::systems::JointStatePublisher">
        <topic>joint_states</topic>
        </plugin>

        <!-- <plugin
        filename="ignition-gazebo-joint-controller-system"
        name="ignition::gazebo::systems::JointController">
        <joint_name>wheelFrontLeft_joint</joint_name>
        <initial_velocity>1.0</initial_velocity>
        </plugin>

        <plugin
        filename="ignition-gazebo-joint-controller-system"
        name="ignition::gazebo::systems::JointController">
        <joint_name>wheelFrontRight_joint</joint_name>
        <initial_velocity>1.0</initial_velocity>
        </plugin>

        <plugin
        filename="ignition-gazebo-joint-controller-system"
        name="ignition::gazebo::systems::JointController">
        <joint_name>wheelBackLeft_joint</joint_name>
        <initial_velocity>1.0</initial_velocity>
        </plugin>

        <plugin
        filename="ignition-gazebo-joint-controller-system"
        name="ignition::gazebo::systems::JointController">
        <joint_name>wheelBackRight_joint</joint_name>
        <initial_velocity>1.0</initial_velocity>
        </plugin> -->

        <plugin
        filename="libignition-gazebo-diff-drive-system.so"
        name="ignition::gazebo::systems::DiffDrive">
          <left_joint>wheelFrontLeft_joint</left_joint>
          <left_joint>wheelBackLeft_joint</left_joint>
          <right_joint>wheelFrontRight_joint</right_joint>
          <right_joint>wheelBackRight_joint</right_joint>
          <wheel_separation>${chassisWidth + wheelWidth}</wheel_separation> <!-- ${chassisWidth + wheelWidth} 0.6177 -->
          <wheel_radius>${wheelRadius}</wheel_radius> <!-- ${wheelRadius} 0.16 -->
          <topic>cmd_vel</topic>
        </plugin>
    </gazebo>

</robot>