<?xml version="1.0" encoding="utf-8"?>

<robot name="robot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="chassisHeight" value="0.66976"/>
    <xacro:property name="chassisLength" value="1.13198"/>
    <xacro:property name="chassisWidth" value="0.5077"/>
    <xacro:property name="chassisMass" value="20"/>
    <xacro:property name="wheelWidth" value="0.11"/>
    <xacro:property name="wheelRadius" value="0.16"/>
    <xacro:property name="wheelMass" value="2"/>

    <!-- Distance between middle - middle front back wheels 0.873175 m -->
    <!-- Distance between middle - middle Left and right wheels 0.62285 m --> <!-- double check, bad mesaurement to middle of wheel -->
    <!-- Distance from back of chassis to middle of back wheels 0.1534125 -->
    <!-- Distance from bottom of chassis to middle of wheels 0.0475 -->

    <xacro:property name="wheelDeltaWidth" value="${(chassisWidth + wheelWidth)/2}" /> <!-- not using messured distance because can calculate it-->
    <xacro:property name="wheelDeltaBack" value="-${chassisLength/2 - 0.1534125}" />
    <xacro:property name="wheelDeltaFront" value="${wheelDeltaBack + 0.873175}" />
    <xacro:property name="wheelDeltaHeight" value="-${chassisHeight/2 - 0.0475}" />

    <xacro:property name="pretty" value="false"/>

    <material name="grey">
        <color
        rgba="0.79216 0.81961 0.93333 1" />
    </material>

    <xacro:include filename="macros.urdf.xacro" />


    <link name="frame_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <xacro:box_inertia m="${chassisMass}" x="${chassisWidth}" y="${chassisLength}" z="${chassisHeight}" />
        </inertial>
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <xacro:if value="${pretty}">
                <mesh
                filename="../meshes/chassis.STL" scale="0.001 0.001 0.001"/> <!-- stl is measured in mm, need m -->
            </xacro:if>
            <xacro:unless value="${pretty}">
                <box size="${chassisWidth} ${chassisLength} ${chassisHeight}"/>
            </xacro:unless>
        </geometry>
        <material name="grey" />
        </visual>
        <collision>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
            <box size="${chassisWidth} ${chassisLength} ${chassisHeight}"/>
        </geometry>
        </collision>
    </link>

    <xacro:wheel_link name="wheelFrontLeft_link" />
        
    <xacro:wheel_joint wheel="wheelFrontLeft" x="-${wheelDeltaWidth}" y="${wheelDeltaFront}" z="${wheelDeltaHeight}"/>
    
    <xacro:wheel_link name="wheelFrontRight_link" />

    <xacro:wheel_joint wheel="wheelFrontRight" x="${wheelDeltaWidth}" y="${wheelDeltaFront}" z="${wheelDeltaHeight}"/>
    
    <xacro:wheel_link name="wheelBackLeft_link" />

    <xacro:wheel_joint wheel="wheelBackLeft" x="-${wheelDeltaWidth}" y="${wheelDeltaBack}" z="${wheelDeltaHeight}"/>
    
    <xacro:wheel_link name="wheelBackRight_link" />

    <xacro:wheel_joint wheel="wheelBackRight" x="${wheelDeltaWidth}" y="${wheelDeltaBack}" z="${wheelDeltaHeight}"/>

</robot>
