<?xml version="1.0" encoding="utf-8"?>

<robot name="robot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="chassisHeight" value="0.64"/>
    <xacro:property name="chassisLength" value="1.1"/>
    <xacro:property name="chassisWidth" value="0.512"/>
    <xacro:property name="chassisMass" value="55"/>
    <xacro:property name="wheelWidth" value="0.11"/>
    <xacro:property name="wheelRadius" value="0.15"/>
    <xacro:property name="wheelMass" value="2"/>

    <xacro:property name="pretty" value="true"/>

    <material name="grey">
        <color
        rgba="0.79216 0.81961 0.93333 1" />
    </material>

    <xacro:include filename="macros.urdf.xacro" />


    <link name="frame_link">
        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${chassisMass}" />
        <inertia
            ixx="0.51975"
            ixy="0"
            ixz="0"
            iyy="0.93889"
            iyz="0"
            izz="0.5273" />
        </inertial>
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <xacro:if value="${pretty}">
                <mesh
                filename="package://robot_description/models/master_ASM/meshes/frame_link.STL" />
            </xacro:if>
            <xacro:unless value="${pretty}">
                <box size="${chassisWidth} ${chassisLength} ${chassisHeight}"/>
            </xacro:unless>
        </geometry>
        <material name="grey" />
        </visual>
        <collision>
        <origin
            xyz="0 0 0"
            rpy="0 0 0" />
        <geometry>
            <box size="${chassisWidth} ${chassisLength} ${chassisHeight}"/>
        </geometry>
        </collision>
    </link>

    <xacro:wheel_link name="wheel1_link" />
        
    <xacro:wheel_joint wheel="wheel1" x="${chassisWidth/2+wheelWidth/3}" y="${chassisLength/2}" z="${chassisHeight/2}"/>
    
    <xacro:wheel_link name="wheel2_link" />

    <xacro:wheel_joint wheel="wheel2" x="${chassisWidth/2+wheelWidth/3}" y="-${chassisLength/2}" z="${chassisHeight/2}"/>
    
    <xacro:wheel_link name="wheel3_link" />

    <xacro:wheel_joint wheel="wheel3" x="-${chassisWidth/2+wheelWidth/3}" y="-${chassisLength/2}" z="${chassisHeight/2}"/>
    
    <xacro:wheel_link name="wheel4_link" />

    <xacro:wheel_joint wheel="wheel4" x="-${chassisWidth/2+wheelWidth/3}" y="${chassisLength/2}" z="${chassisHeight/2}"/>

</robot>