/**:
  ros__parameters:
    # multi mapper
    mapping_type: "dynamic"
    # lidar settings
    use_lidar: false

    static_mapper:
      # projective integrator (tsdf/color)
      projective_integrator_max_integration_distance_m: 4.0
      # freespace integrator
      max_tsdf_distance_for_occupancy_m: 0.15
      max_unobserved_to_keep_consecutive_occupancy_ms: 200
      min_duration_since_occupied_for_freespace_ms: 250
      min_consecutive_occupancy_duration_for_reset_ms: 2000
      check_neighborhood: true

    dynamic_mapper:
      # occupancy integrator
      projective_integrator_max_integration_distance_m: 4.0
      projective_integrator_truncation_distance_vox: 4.0
      free_region_occupancy_probability: 0.2
      occupied_region_occupancy_probability: 0.9
      unobserved_region_occupancy_probability: 0.35
      occupied_region_half_width_m: 0.15
      # esdf integrator
      esdf_integrator_min_weight: 2.0
      esdf_integrator_max_distance_m: 2.0
      esdf_integrator_max_site_distance_vox: 5.0
      # occupancy decay integrator
      free_region_decay_probability: 0.55
      occupied_region_decay_probability: 0.25
