FROM ubuntu:22.04

# Switch to root to perform installations
USER root

# Avoid interactive prompts during apt-get steps
ENV DEBIAN_FRONTEND=noninteractive

RUN groupadd -g 110 input_host 2>/dev/null || true

# Install base dependencies
RUN apt-get update && \
    apt-get install -y git-lfs xz-utils curl wget build-essential iproute2 can-utils evtest && \
    rm -rf /var/lib/apt/lists/*

# Install Zig 0.16.0
WORKDIR /opt
ARG ZIG_VERSION="0.16.0"
ARG ZIG_ARCH
ARG TARGETARCH
RUN echo "Building for Operating System: and Architecture: $TARGETARCH"
RUN set -eux; \
    if [ "$TARGETARCH" = "amd64" ]; then \
    ZIG_ARCH="x86_64"; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    ZIG_ARCH="aarch64"; \
    else \
    ZIG_ARCH="$TARGETARCH"; \
    fi; \
    echo "Mapped architecture is: $ZIG_ARCH"; \
    curl -LO https://ziglang.org/download/${ZIG_VERSION}/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}.tar.xz; \
    tar -xf zig-${ZIG_ARCH}-linux-${ZIG_VERSION}.tar.xz; \
    rm zig-${ZIG_ARCH}-linux-${ZIG_VERSION}.tar.xz; \
    ln -s /opt/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}/zig /usr/local/bin;

# Ensure root owns the workspace
RUN mkdir -p /workspaces/isaac_ros-dev && chown -R root:root /workspaces/isaac_ros-dev

# Accept the host path as a build argument (with a safe default fallback)
ARG HOST_PROJECT_PATH=/tmp/default_workspace

# Create the parent directory structure and symlink it to the container's workspace
RUN mkdir -p "$(dirname "$HOST_PROJECT_PATH")" && \
    ln -s /workspaces/isaac_ros-dev "$HOST_PROJECT_PATH"

# Linking .zig-cache like this fixes an error when running 'zig build' on Windows
RUN set -eux; \
    mkdir /tmp/.zig-cache; \
    ln -s /tmp/.zig-cache /workspaces/isaac_ros-dev;

# Create entrypoint script inside root's home directory (/root/)
RUN echo '#!/bin/bash\nexec "$@"' > /root/entrypoint.sh && chmod +x /root/entrypoint.sh

ENTRYPOINT ["/root/entrypoint.sh"]
CMD ["bash"]