ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY deepstream/deepstream.deb deepstream.deb

RUN --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    libgstrtspserver-1.0-dev \
    ./deepstream.deb && \
    rm deepstream.deb && \
    rm -rf /var/lib/apt/lists/*
