ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y \
    ros-humble-ros-gz \
    ros-humble-sdformat-urdf \
    ros-humble-joint-state-publisher-gui \
    && rm -rf /var/lib/apt/lists/*
