
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root
RUN apt-get update && \
    apt-get install -y \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly && \
    rm -rf /var/lib/apt/lists/*

COPY deepstream/deepstream.deb deepstream.deb

RUN apt-get update && apt-get install -y ./deepstream.deb && \
    rm deepstream.deb && \
    rm -rf /var/lib/apt/lists/*

