# Base Image
FROM stereolabs/zed:4.0-devel-cuda11.8-ubuntu20.04

# Disable debian interactive mode
ENV DEBIAN_FRONTEND=noninteractive
# Set ROS distro
ENV ROS_DISTRO=humble
# Suppress the setuptools deprecated warning
ENV PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"

# Add keys and sources for ROS 2 Humble need to install from source because jetpack hasn't been released yet
RUN apt update && apt install curl -y && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt update && sudo apt install -y \
    python3-flake8-docstrings \
    python3-pip \
    python3-pytest-cov \
    ros-dev-tools && \
    python3 -m pip install -U \
    flake8-blind-except \
    flake8-builtins \
    flake8-class-newline \
    flake8-comprehensions \
    flake8-deprecated \
    flake8-import-order \
    flake8-quotes \
    "pytest>=5.3" \
    pytest-repeat \
    pytest-rerunfailures && \
    mkdir -p ~/ros2_humble/src && \
    cd ~/ros2_humble && \
    vcs import --input https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos src && \
    rosdep init && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers"
RUN cd ~/ros2_humble && \
    colcon build --symlink-install 

# Add Local workspace dependencies
COPY my.repos /root/ros2_humble/
RUN vcs import --input my.repos src && \
    rm my.repos && \
    cd ~/ros2_humble && \
    rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers" && \
    colcon build --symlink-install
# Source ROS 2 Humble in .bashrc
RUN echo "source ~/ros2_humble/install/local_setup.bash" >> ~/.bashrc
# Source our ROS 2 workspace in .bashrc
RUN echo "source install/setup.bash" >> ~/.bashrc