ARG BASE
FROM ${BASE}

# Force update cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.27.3/cmake-3.27.3-linux-x86_64.sh && \
    chmod +x cmake-3.27.3-linux-x86_64.sh && \
    ./cmake-3.27.3-linux-x86_64.sh --skip-license && \
    rm cmake-3.27.3-linux-x86_64.sh

