# Base Image
FROM ros:humble

# Disable debian interactive mode
ENV DEBIAN_FRONTEND=noninteractive
# Set ROS distro
ENV ROS_DISTRO=humble
# Suppress the setuptools deprecated warning
ENV PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"

# Check the CPU architecture
ARG TARGETARCH

# Install git and openssh-server
RUN apt-get update && apt-get install -y \
    git \
    openssh-server \
    python3-pip

# Install the ZED SDK (Required for the ZED ROS2 Wrapper)
RUN if [ "$TARGETARCH" = "x86_64" ] || [ "$TARGETARCH" = "amd64" ]; then \
        echo "Building for x86 architecture"; \
        apt-get update -y || true ; apt-get install --no-install-recommends lsb-release wget less udev sudo zstd build-essential cmake python3 python3-pip libpng-dev libgomp1 -y ; \
        python3 -m pip install numpy opencv-python ; \
        wget -q -O ZED_SDK_Linux_Ubuntu22.run https://download.stereolabs.com/zedsdk/4.0/cu121/ubuntu22 && \
        chmod +x ZED_SDK_Linux_Ubuntu22.run ; ./ZED_SDK_Linux_Ubuntu22.run -- silent skip_tools && \
        ln -sf /lib/x86_64-linux-gnu/libusb-1.0.so.0 /usr/lib/x86_64-linux-gnu/libusb-1.0.so && \
        rm ZED_SDK_Linux_Ubuntu22.run && \
        rm -rf /var/lib/apt/lists/* ; \
    elif [ "$TARGETARCH" = "aarch64" ] || [ "$TARGETARCH" = "arm64" ]; then \
        echo "Building for ARM architecture"; \
        echo "# R${L4T_MAJOR} (release), REVISION: ${L4T_MINOR}" > /etc/nv_tegra_release && \
        apt-get update -y || true && \
        apt-get install -y --no-install-recommends zstd wget less cmake curl gnupg2 \
        build-essential python3 python3-pip python3-dev python3-setuptools libusb-1.0-0-dev -y && \
        pip install protobuf && \
        wget -q --no-check-certificate -O ZED_SDK_Linux_JP.run \
        https://download.stereolabs.com/zedsdk/4.0/l4t35.3/jetsons && \
        chmod +x ZED_SDK_Linux_JP.run ; ./ZED_SDK_Linux_JP.run silent skip_tools && \
        rm -rf /usr/local/zed/resources/* && \
        rm -rf ZED_SDK_Linux_JP.run && \
        rm -rf /var/lib/apt/lists/* ; \
    else \
        echo "Unsupported architecture"; \
        exit 1; \
    fi

# Source ROS 2 Humble in .bashrc
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
# Source our ROS 2 workspace in .bashrc
RUN echo "source install/setup.bash" >> ~/.bashrc