/**:
  ros__parameters:
    #TODO: Figure out all of these values
    SCREW_SPEED: 4000 # TODO: update
    POWER_LIMIT: 1 #TODO: update
    FAST_SCREW_SPEED: 8000 #0.21
    extension_limit_switch: true
    STOWED: true
    MAX_PUSH_MOTOR_POSITION: 10000
    MIN_PUSH_MOTOR_POSITION: 1000
    PUSH_MOTOR_POS_TOLERANCE: 0
    MAX_PUSH_MOTOR_VELOCITY: 0
    TILT_ACTUATOR_SPEED: 1.0
    TILT_ACTUATOR_MIN_EXTENSION: 0
    TILT_ACTUATOR_ID: 1
    PUSH_MOTOR_ID: 3
    SPIN_MOTOR_ID: 4