behavior_control_node:
  ros__parameters:
    groot_publisher_port: 1667
    behavior_tree_file: "/tree/main_tree.xml"
    behaviort_tree_tick_interval: 10 # ms

    # Xbox / Joystick Buttons
    buttons:
      X_BUTTON: 0
      A_BUTTON: 1
      B_BUTTON: 2
      Y_BUTTON: 3
      LEFT_BUMPER: 4
      RIGHT_BUMPER: 5
      LEFT_TRIGGER: 6
      RIGHT_TRIGGER: 7
      BACK_BUTTON: 8
      START_BUTTON: 9
      LEFT_JOYSTICK_BUTTON: 10
      RIGHT_JOYSTICK_BUTTON: 11

    # Xbox / Joystick Axes
    axes:
      LEFT_JOYSTICK_HORIZONTAL: 0
      LEFT_JOYSTICK_VERTICAL: 1
      RIGHT_JOYSTICK_HORIZONTAL: 2
      RIGHT_JOYSTICK_VERTICAL: 3

    # StreamDeck Buttons
    streamdeck:
      START_AUTO: 0
      AUTO_DIG: 1
      AUTO_DUMP: 2
      APRILTAG_DETECT: 3
      GO_TO_DIG_SITE: 4
      ESTOP: 5
  
    # Motor / Acuator CAN ids
    # TODO: These are just examples, add more
    hardware:
      SPIN_MOTOR: 5
      PUSH_MOTOR: 6
      TILT_ACTUATOR: 7
      BACK_LEFT_DRIVE: 5 # CAN ID of the back left drive motor
      FRONT_LEFT_DRIVE: 3 # CAN ID of the front left drive motor
      BACK_RIGHT_DRIVE: 1 # CAN ID of the back right drive motor
      FRONT_RIGHT_DRIVE: 6 # CAN ID of the front right drive motor
      DIGGER_MOTOR: 10 # CAN ID of the digger chain motor
      DIGGER_LEFT_LINEAR_ACTUATOR: 8 # CAN ID of the left linear actuator
      DIGGER_RIGHT_LINEAR_ACTUATOR: 7 # CAN ID of the right linear actuator
      DUMPER_MOTOR: 2 # CAN ID of the dumper motor