drivetrain_node:
  ros__parameters:
        WHEEL_BASE: 0.5  # HALF of the wheelbase length in meters # TODO: Change this value when we know the final measurement
        TRACK_WIDTH: 0.5  # HALF of the trackwidth length in meters # TODO: Change this value when we know the final measurement
