---
# - ros_topic_name: "/cmd_vel"
#   gz_topic_name: "/model/vehicle_blue/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
# - ros_topic_name: "/mecanum_drive/odometry"
#   gz_topic_name: "/model/mecanum_drive/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/mecanum_drive/scan"
#   gz_topic_name: "/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/world/demo/model/mecanum_drive/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/tf"
#   gz_topic_name: "/model/mecanum_drive/pose"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/tf_static"
#   gz_topic_name: "/model/mecanum_drive/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

- ros_topic_name: "/wheel1/cmd_vel"
  gz_topic_name: "/model/Master_ASM/joint/wheel1_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/wheel2/cmd_vel"
  gz_topic_name: "/model/Master_ASM/joint/wheel2_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/wheel3/cmd_vel"
  gz_topic_name: "/model/Master_ASM/joint/wheel3_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/wheel4/cmd_vel"
  gz_topic_name: "/model/Master_ASM/joint/wheel4_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/swerve1/cmd_pos"
  gz_topic_name: "/model/Master_ASM/joint/swerve1_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/swerve2/cmd_pos"
  gz_topic_name: "/model/Master_ASM/joint/swerve2_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/swerve3/cmd_pos"
  gz_topic_name: "/model/Master_ASM/joint/swerve3_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/swerve4/cmd_pos"
  gz_topic_name: "/model/Master_ASM/joint/swerve4_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
