# Define all the buttons here
X_BUTTON = 0
A_BUTTON = 1
B_BUTTON = 2
Y_BUTTON = 3
LEFT_BUMPER = 4
RIGHT_BUMPER = 5
LEFT_TRIGGER = 6
RIGHT_TRIGGER = 7
BACK_BUTTON = 8
START_BUTTON = 9
LEFT_JOYSTICK_BUTTON = 10
RIGHT_JOYSTICK_BUTTON = 11

# Define all the axes here
LEFT_JOYSTICK_HORIZONTAL_AXIS = 0
LEFT_JOYSTICK_VERTICAL_AXIS = 1
RIGHT_JOYSTICK_HORIZONTAL_AXIS = 2
RIGHT_JOYSTICK_VERTICAL_AXIS = 3

# Define streamdeck buttons here
STREAMDECK_START_AUTO = 0
STREAMDECK_AUTO_DIG = 1
STREAMDECK_AUTO_DUMP = 2
STREAMDECK_APRILTAG_DETECT = 3
STREAMDECK_GO_TO_DIG_SITE = 4
STREAMDECK_ESTOP = 5
