# Define all the buttons here
X_BUTTON = 2
A_BUTTON = 0
B_BUTTON = 1
Y_BUTTON = 3
LEFT_BUMPER = 4
RIGHT_BUMPER = 5
BACK_BUTTON = 6
START_BUTTON = 7
XBOX_BUTTON = 8
LEFT_JOYSTICK_BUTTON = 9
RIGHT_JOYSTICK_BUTTON = 10

# Define all the axes here
LEFT_JOYSTICK_HORIZONTAL_AXIS = 0
LEFT_JOYSTICK_VERTICAL_AXIS = 1
RIGHT_JOYSTICK_HORIZONTAL_AXIS = 3
RIGHT_JOYSTICK_VERTICAL_AXIS = 4
LEFT_TRIGGER_AXIS = 2
RIGHT_TRIGGER_AXIS = 5
DPAD_HORIZONTAL_AXIS = 6
DPAD_VERTICAL_AXIS = 7
