/**:
  ros__parameters:
    # miscellaneous
    voxel_size: 0.05
    use_tf_transforms: true
    # multi mapper
    mapping_type: "static_tsdf"  # ["static_tsdf", "static_occupancy"]
    connected_mask_component_size_threshold: 2000
    # esdf settings
    compute_esdf: true
    esdf_update_rate_hz: 10.0
    esdf_2d: false
    publish_esdf_distance_slice: true
    
    esdf_2d_min_height: -1.5
    esdf_2d_max_height: 1.0
    # mesh settings
    compute_mesh: true
    mesh_update_rate_hz: 2.0
    # color settings
    use_color: true
    max_color_update_hz: 5.0
    # depth settings
    use_depth: true
    max_depth_update_hz: 30.0
    # static occupancy
    static_occupancy_publication_rate_hz: 2.0
    # dynamic occupancy
    dynamic_occupancy_decay_rate_hz: 10.0
    # Input queues
    max_poll_rate_hz: 100.0
    maximum_sensor_message_queue_length: 30
    # Map clearing settings
    map_clearing_radius_m: -1.0 # no map clearing if < 0.0
    map_clearing_frame_id: "zed2i_camera_link"
    clear_outside_radius_rate_hz: 1.0
    # QoS settings
    depth_qos: "SYSTEM_DEFAULT"
    color_qos: "SYSTEM_DEFAULT"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "zed2i_camera_link"
    slice_visualization_side_length: 10.0

    # Used for crater detection.
    # one is the floor, two is hole level
    # by going significantly above 'ground', we ignore all the noise from uneven terrain while still detecting obstacles.
    esdf_above_ground_slice_height: 0.4  # TODO: This might need to be adjusted
    esdf_underground_detection: -1.0  # TODO: This might need to be adjusted
    combine_pointcloud: True
    combine_costmap: True
    invert_below_ground: False
    above_ground_denoise_level: 0.5

    static_mapper:
      # mapper
      do_depth_preprocessing: false
      depth_preprocessing_num_dilations: 3
      # projective integrator (tsdf/color/occupancy)
      projective_integrator_max_integration_distance_m: 7.0
      lidar_projective_integrator_max_integration_distance_m: 10.0
      projective_integrator_truncation_distance_vox: 4.0
      weighting_mode: "inverse_square_tsdf_distance_penalty"
      projective_integrator_max_weight: 5.0
      # occupancy integrator
      free_region_occupancy_probability: 0.45
      occupied_region_occupancy_probability: 0.55
      unobserved_region_occupancy_probability: 0.5
      occupied_region_half_width_m: 0.1
      # esdf integrator
      esdf_integrator_min_weight: 0.0001
      esdf_integrator_max_site_distance_vox: 5.0
      esdf_integrator_max_distance_m: 2.0
      # mesh integrator
      mesh_integrator_min_weight: 0.0001
      mesh_integrator_weld_vertices: true
      # tsdf decay integrator
      tsdf_decay_factor: 0.95
